export const proposalResumeObject = [
  { key: 'baseValue', label: 'Base value (€)' },
  { key: 'workScheduleExemption', label: 'Work schedule exemption (%)' },
  { key: 'workScheduleExemptionValue', label: 'Work schedule exemption value (€)' },
  { key: 'irsTax', label: 'IRS tax (%)' },
  { key: 'vacationsTwelfth', label: 'Vacations twelfth (€)' },
  { key: 'christmasTwelfth', label: 'Christmas twelfth (€)' },
  { key: 'otherExpenses', label: 'Other expenses (€)' },
  { key: 'remoteWorkAllowance', label: 'Remote work allowance (€)' },
  { key: 'communicationsPlafond', label: 'Communications plafond (€)' },
  { key: 'healthInsurance', label: 'Health insurance (€)' },
  { key: 'includeFamilymembers', label: 'Include family members' },
  { key: 'numberFamilyMembers', label: 'Number family members' },
  { key: 'familyMembersValue', label: 'Family members value (€)' },
  { key: 'baseValueSocialSecurity', label: 'Base value social security (€)' },
  { key: 'christmasAllowanceTwelfthSocialSecurity', label: 'Christmas allowance twelfth social security (€)' },
  { key: 'vacationsAllowanceTwelfthSocialSecurity', label: 'Vacations allowance twelfth social security (€)' },
  { key: 'baseValueIRS', label: 'Base value IRS (€)' },
  { key: 'christmasAllowanceTwelfthAllowanceIRS', label: 'Christmas allowance twelfth allowance IRS (€)' },
  { key: 'vacationsAllowanceTwelfthAllowanceIRS', label: 'Vacations allowance twelfth allowance IRS (€)' },
  { key: 'monthlyGrossValue', label: 'Monthly gross value (€)' },
  { key: 'monthlyNetValue', label: 'Monthly net value (€)' },
  { key: 'anualGrossValue', label: 'Anual gross value (€)' },
  { key: 'anualNetValue', label: 'Anual net value (€)' },
  { key: 'monthlyBenefits', label: 'Monthly benefits (€)' },
  { key: 'anualBenefits', label: 'Anual benefits (€)' },
  { key: 'annualCosts', label: 'Annual costs (€)' },
  { key: 'monthlyCosts', label: 'Monthly costs (€)' },
  { key: 'dailyCosts', label: 'Daily costs (€)' }
]
